### ISSUE TITLE
Issues while building in Noetic + 20.04

### ISSUE THREAD

**Issue by AKC141096** [verlab/3d-object-semantic-mapping#6]
Hello,

I am trying to build this repo using catkin build in Ubuntu 20.04 & ROS -Noetic.
All other packages build fine except for the 'Auto' package.

The error seems to be related to pcl-conversions/ pcl-ros but I am unable to resolve it.

I have attached the entire error message.
[PCL-conversions' error.odt](https://github.com/verlab/3DSemanticMapping_JINT_2020/files/8715224/PCL-conversions.error.odt)

Any help would be greatly appreciated!

**Comment by KalanaRatnayake** [comment]
Try replacing following snippet in auto/CMakeLists.txt
```
# check c++11 / c++0x
include(CheckCXXCompilerFlag)
CHECK_CXX_COMPILER_FLAG("-std=c++11" COMPILER_SUPPORTS_CXX11)
CHECK_CXX_COMPILER_FLAG("-std=c++0x" COMPILER_SUPPORTS_CXX0X)
if(COMPILER_SUPPORTS_CXX11)
    set(CMAKE_CXX_FLAGS "-std=c++11")
elseif(COMPILER_SUPPORTS_CXX0X)
    set(CMAKE_CXX_FLAGS "-std=c++0x")
else()
    message(FATAL_ERROR "The compiler ${CMAKE_CXX_COMPILER} has no C++11 support. Please use a different C++ compiler.")
endif()
```

with 

```
# check c++14/  c++11 / c++0x
include(CheckCXXCompilerFlag)
CHECK_CXX_COMPILER_FLAG("-std=c++14" COMPILER_SUPPORTS_CXX14)
CHECK_CXX_COMPILER_FLAG("-std=c++11" COMPILER_SUPPORTS_CXX11)
CHECK_CXX_COMPILER_FLAG("-std=c++0x" COMPILER_SUPPORTS_CXX0X)
if(COMPILER_SUPPORTS_CXX14)
    set(CMAKE_CXX_FLAGS "-std=c++14")
elseif(COMPILER_SUPPORTS_CXX11)
    set(CMAKE_CXX_FLAGS "-std=c++11")
elseif(COMPILER_SUPPORTS_CXX0X)
    set(CMAKE_CXX_FLAGS "-std=c++0x")
else()
    message(FATAL_ERROR "The compiler ${CMAKE_CXX_COMPILER} has no C++11 support. Please use a different C++ compiler.")
endif()
```

pcl_ros include files for ubuntu uses c++14 syntax. so if you try to build with c++11 it fails.

**Comment by AKC141096** [comment]
Hello,

Thank you for your response.

Yes, this does seem to work. I did something similar. I just did.

set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

and commented out the other CMAKE related lines.
